# Generated by Django 5.2.3 on 2025-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menulink",
            name="restaurant_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
