# Generated by Django 5.2.3 on 2025-06-13 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menulink_restaurant_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="menulink",
            unique_together={("user", "restaurant_name")},
        ),
    ]
