# Generated by Django 5.2.3 on 2025-06-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_menuitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["section__order", "section__name", "name"],
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="menu.menulink",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("menu", "name")},
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="menu.menusection",
            ),
        ),
    ]
