# Generated by Django 5.2.3 on 2025-06-13 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_menuitem_options_menusection_menuitem_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["section__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="menulink",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menusection",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="menulink",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="menusection",
            name="description",
        ),
        migrations.RemoveField(
            model_name="menusection",
            name="order",
        ),
        migrations.AddField(
            model_name="menulink",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.menulink",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="restaurant_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="menulink",
            name="website_link",
        ),
    ]
