# Generated by Django 5.2.3 on 2025-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_menuitem_options_alter_menulink_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menulink",
            name="restaurant_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_images/"
            ),
        ),
    ]
