# Generated by Django 5.2.3 on 2025-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_menulink_restaurant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menulink",
            name="template",
            field=models.CharField(
                choices=[
                    ("classic", "Classic Menu"),
                    ("modern", "Modern Menu"),
                    ("minimal", "Minimal Menu"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
