# Generated by Django 5.2.3 on 2025-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0009_remove_menulink_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="tagline",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
