# Generated by Django 5.2.3 on 2025-06-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0011_menutemplate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuTemplate",
        ),
    ]
