# Generated by Django 5.2.3 on 2025-06-15 15:18

import django.db.models.deletion
from django.db import migrations, models

def create_default_templates(apps, schema_editor):
    MenuTemplate = apps.get_model('menu', 'MenuTemplate')
    
    templates = [
        {
            'name': 'Classic',
            'description': 'Traditional menu layout',
            'template_file': 'classic.html'
        },
        {
            'name': 'Modern',
            'description': 'Contemporary design',
            'template_file': 'modern.html'
        },
        {
            'name': 'Minimal',
            'description': 'Clean and simple',
            'template_file': 'minimal.html'
        }
    ]
    
    for template_data in templates:
        MenuTemplate.objects.create(**template_data)

class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0012_delete_menutemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("template_file", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="template_thumbnails/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="menulink",
            name="old_template",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RunPython(create_default_templates),
        migrations.AlterField(
            model_name="menulink",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.menutemplate",
            ),
        ),
    ]
