# Generated by Django 5.2.3 on 2025-06-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0014_convert_templates"),
        ("menu", "0014_update_template_references"),
    ]

    operations = []
