# Generated by Django 5.2.3 on 2025-06-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0015_merge_20250615_2049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menulink",
            name="old_template",
        ),
    ]
