# Generated by Django 5.2.3 on 2025-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0016_remove_menulink_old_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_images/"
            ),
        ),
    ]
