# Generated by Django 5.2.3 on 2025-06-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0018_remove_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menusection",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="menusection",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="restaurant",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.menulink"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.menusection",
            ),
        ),
        migrations.AlterField(
            model_name="menusection",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.menulink"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="tagline",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
