# Generated by Django 5.2.3 on 2025-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_restaurant_owner",
            field=models.BooleanField(default=False),
        ),
    ]
