# Generated by Django 5.2.3 on 2025-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_restaurant_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
