# Generated by Django 5.2.3 on 2025-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verification_token_created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
