# Generated by Django 5.2.3 on 2025-06-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_phone_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_verification_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_verification_token_created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_verified",
        ),
    ]
