# Generated by Django 5.2.3 on 2025-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_phone_verification_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("is_restaurant_owner", models.BooleanField(default=False)),
                ("email_verification_token", models.CharField(max_length=6)),
                (
                    "email_verification_token_created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),
    ]
