# Generated by Django 5.2.3 on 2025-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_registrationdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username_verification_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username_verification_token_created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username_verified",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
